.TH JACK.RECORD "1" 0.1 "March 2004"
.SH NAME
jack.backup \- JACK Capture Client
.SH SYNOPSIS
.BR jack.backup
.RI [ options ]
.I sound-file
.SH OPTIONS
.TP
.B \-b
Set the disk buffer size in frames (default=4096).  This value must be
a power of two.  If the JACK period size at any time exceeds this
value the recorder will halt.
.TP
.B \-f
Set the file format (default=0x10006).  The number is a bitwise-or of
two values, the first describes the file type, the second the data
type.  The default value of 0x10000 | 0x00006 describes a thirty-two
bit floating point WAV file.
.TP
.B \-m
Set the minimal disk transfer size in frames (default=32). This is an
optimization switch.
.TP
.B \-n
Set the number of input channels to create (default=2).
.TP
.B \-s
Capture to a set of single channel sound files.  The sound file name
must be a valid template.
.TP
.B \-t
Set a timer to stop the recording after the specified number of
seconds (default=-1).
.SH DESCRIPTION
.B jack.backup
is a light-weight 
.B JACK
capture client to write an arbitrary number of channels to disk.  It
implements no connection logic, use
.BR jack.plumbing (1)
instead.
.PP
If the default mode a single multiple channel sound file is written.  If the 
.B \-s
option is given a set of single channel sound files are written.  In
this case the sound file name must be a valid template, the substring
.I %d
is replaced with the channel number counting from zero.
.PP
.B jack.backup
will write files in any format supported by
.BR libsndfile .
The table below shows the most common file format masks.  For other
values see the file
.IR sndfile.h .
.IP
.TS
;
lb li l .
SF_FORMAT_WAV	0x10000	Microsoft WAV format
SF_FORMAT_AIFF	0x20000	Apple/SGI AIFF format
SF_FORMAT_PCM_16	0x00002	Signed 16 bit data
SF_FORMAT_PCM_24	0x00003	Signed 24 bit data
SF_FORMAT_PCM_32	0x00004	Signed 32 bit data
SF_FORMAT_FLOAT	0x00006	32 bit float data
.TE
.SH AUTHOR
Rohan Drape <http://www.alphalink.com.au/~rd/>.
.SH SEE ALSO
.BR jackd "(1), " libsndfile "(3) <http://www.zip.com.au/~erikd/libsndfile/>"
